# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_auto_20160819_1101'),
        ('courses_model', '0003_auto_20160816_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login_reg_app.User'),
            preserve_default=False,
        ),
    ]
